workflows: fix in-cluster job kubectl wait
[ cherry-picked from cilium/cilium-cli repository ]

`kubectl wait --for=condition=complete --timeout=X` behaviour is a bit
counterintuitive: it waits until either the job succeeds or timeout is
hit. When the job fails, it does not stop waiting: it will continue
waiting until timeout is hit.

For watching for failures, `--for=condition=failed` should be used.
However, this will likewise wait until either the job fails or timeout
is hit, and will not stop waiting if the job succeeds.

`kubectl wait` unfortunately does not allow waiting for multiple
conditions. To work around this, we set up two concurrent background
waits for both conditions, and actively wait for the first one to end.

This will ensure we do not wait for the whole allocated timeout
everytime there is an error during the in-cluster script execution.

Signed-off-by: Nicolas Busseneau <nicolas@isovalent.com>

diff --git a/cilium-cli/.github/workflows/aks.yaml b/cilium-cli/.github/workflows/aks.yaml
--- a/cilium-cli/.github/workflows/aks.yaml
+++ b/cilium-cli/.github/workflows/aks.yaml
@@ -160,8 +160,20 @@ jobs:
             --set azure.client_secret=${{ steps.az.outputs.client-secret }}
 
       - name: Wait for install job
+        env:
+          timeout: 5m
         run: |
-          kubectl -n kube-system wait job/cilium-cli-install --for=condition=complete --timeout=5m
+          # Background wait for job to complete or timeout
+          kubectl -n kube-system wait job/cilium-cli-install --for=condition=complete --timeout=${{ env.timeout }} &
+          complete_pid=$!
+
+          # Background wait for job to fail
+          (kubectl -n kube-system wait job/cilium-cli-install --for=condition=failed --timeout=${{ env.timeout }} && exit 1) &
+          failed_pid=$!
+
+          # Active wait for whichever background process ends first
+          wait -n $complete_pid $failed_pid
+          exit $?
 
       - name: Delete the first node pool
         run: |
@@ -183,9 +195,21 @@ jobs:
           helm install .github/cilium-cli-test-job-chart \
             --generate-name
 
-      - name: Wait for job
+      - name: Wait for test job
+        env:
+          timeout: 15m
         run: |
-          kubectl -n kube-system wait job/cilium-cli --for=condition=complete --timeout=15m
+          # Background wait for job to complete or timeout
+          kubectl -n kube-system wait job/cilium-cli --for=condition=complete --timeout=${{ env.timeout }} &
+          complete_pid=$!
+
+          # Background wait for job to fail
+          (kubectl -n kube-system wait job/cilium-cli --for=condition=failed --timeout=${{ env.timeout }} && exit 1) &
+          failed_pid=$!
+
+          # Active wait for whichever background process ends first
+          wait -n $complete_pid $failed_pid
+          exit $?
 
       - name: Post-test information gathering
         if: ${{ !success() }}
