contrib: Warn user when backport branch exists
[ upstream commit 5cfa8a88d5b91d3370b8db3009e43fc7e7f327d9 ]

Signed-off-by: Chris Tarazi <chris@isovalent.com>
Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>

diff --git a/contrib/backporting/start-backport b/contrib/backporting/start-backport
--- a/contrib/backporting/start-backport
+++ b/contrib/backporting/start-backport
@@ -39,5 +39,16 @@ if ! git branch -a | grep -q "origin/v$BRANCH$" ; then
 fi
 
 DATE=$(date --rfc-3339=date)
-git checkout -b "pr/v$BRANCH-backport-$DATE${SUFFIX}" origin/v$BRANCH
+PRBRANCH="pr/v${BRANCH}-backport-${DATE}${SUFFIX}"
+
+if ! (git --no-pager branch | grep -q "${PRBRANCH}"); then
+    echo "Error: branch '${PRBRANCH}' already exists"
+    echo "Consider passing a suffix as the second parameter"
+    echo
+    echo "Example:"
+    echo "  ./contrib/backporting/start-backport ${BRANCH} \"-2\""
+    common::exit 1
+fi
+
+git checkout -b "${PRBRANCH}" origin/v$BRANCH
 contrib/backporting/check-stable $BRANCH v$BRANCH-backport-$DATE.txt
