.github/workflows: fail the job if the input was a failure
Besides reporting in the commit SHA if the test was or not successful,
we should also report it in the workflow itself. This will allow to
store the failure rate of the workflow on OpenSearch, instead of
marking it as successful.

Signed-off-by: André Martins <andre@cilium.io>

diff --git a/.github/workflows/common-post-jobs.yaml b/.github/workflows/common-post-jobs.yaml
--- a/.github/workflows/common-post-jobs.yaml
+++ b/.github/workflows/common-post-jobs.yaml
@@ -55,3 +55,17 @@ jobs:
         with:
           sha: ${{ inputs.sha }}
           status: ${{ inputs.success && 'success' || 'failure' }}
+
+  fail-workflow:
+    if: ${{ inputs.success == false }}
+    name: Fail job if result is failure
+    runs-on: ubuntu-24.04
+    steps:
+      - name: Fail job if result is failure
+        # Besides reporting in the commit SHA if the test was or not successful,
+        # we should also report it in the workflow itself. This will allow to
+        # store the failure rate of the workflow on OpenSearch, instead of
+        # marking it as successful.
+        run: |
+          echo "::error::Workflow failed because one or more jobs failed"
+          exit 1
