Run tests.
Signed-off-by: viktor-kurchenko <viktor.kurchenko@isovalent.com>

diff --git a/.github/workflows/conformance-aks-v1.11.yaml b/.github/workflows/conformance-aks-v1.11.yaml
--- a/.github/workflows/conformance-aks-v1.11.yaml
+++ b/.github/workflows/conformance-aks-v1.11.yaml
@@ -1,4 +1,4 @@
-name: ConformanceGKE (ci-gke-1.11)
+name: ConformanceAKS (ci-aks-1.11)
 
 # Any change in triggers needs to be reflected in the concurrency group.
 on:
@@ -7,7 +7,7 @@ on:
 #      - created
 #  # Run once a day
 #  schedule:
-#    - cron:  '0 3 * * *'
+#    - cron:  '0 13 * * *'
   ### FOR TESTING PURPOSES
   # This workflow runs in the context of `main`, and ignores changes to
   # workflow files in PRs. For testing changes to this workflow from a PR:
@@ -19,7 +19,7 @@ on:
   # - Don't forget to remove the `DO NOT MERGE` commit once satisfied. The run
   #   will disappear from the PR checks: please provide a direct link to the
   #   successful workflow run (can be found from Actions tab) in a comment.
-  #
+  # 
   pull_request: {}
   ###
 
@@ -32,6 +32,8 @@ permissions:
   pull-requests: read
   # So that Sibz/github-status-action can write into the status API
   statuses: write
+  # Required to generate OIDC tokens for `az` authentication
+  id-token: write
 
 concurrency:
   # Structure:
@@ -56,7 +58,7 @@ concurrency:
     ${{
       (github.event_name == 'schedule' && github.sha) ||
       (github.event_name == 'issue_comment' && (
-        github.event.comment.body == '/ci-gke-1.11' ||
+        github.event.comment.body == '/ci-aks-1.11' ||
         github.event.comment.body == '/test-backport-1.11'
       ) && github.event.issue.number) ||
       (github.event_name == 'pull_request' && github.event.pull_request.number)
@@ -64,19 +66,19 @@ concurrency:
   cancel-in-progress: true
 
 env:
-  clusterName: ${{ github.repository_owner }}-${{ github.event.repository.name }}-${{ github.run_id }}
+  name: ${{ github.repository_owner }}-${{ github.event.repository.name }}-${{ github.run_id }}
+  cost_reduction: --node-vm-size Standard_B2s --node-osdisk-size 30
   # renovate: datasource=github-releases depName=cilium/cilium-cli
   cilium_cli_version: v0.14.7
   cilium_cli_ci_version:
   check_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
-  USE_GKE_GCLOUD_AUTH_PLUGIN: True
 
 jobs:
   check_changes:
     name: Deduce required tests from code changes
     if: |
       (github.event_name == 'issue_comment' && (
-        github.event.comment.body == '/ci-gke-1.11' ||
+        github.event.comment.body == '/ci-aks-1.11' ||
         github.event.comment.body == '/test-backport-1.11'
       )) ||
       github.event_name == 'schedule' ||
@@ -152,7 +154,7 @@ jobs:
   skip-test-run:
     # If the modified files are not relevant for this test then we can skip
     # this test and mark it as successful.
-    if: github.event.comment.body == '/test-backport-1.11' && needs.check_changes.outputs.tested == 'false'
+    if: github.event.comment.body == '/test' && needs.check_changes.outputs.tested == 'false'
     runs-on: ubuntu-latest
     needs: setup-report
     name: Set commit status to success (skipped)
@@ -181,28 +183,21 @@ jobs:
 
       - name: Convert YAML to JSON
         run: |
-          work_dir=".github/actions/gke"
-          destination_directory="/tmp/generated/gke"
+          work_dir=".github/actions/azure"
+          destination_directory="/tmp/generated/azure"
           mkdir -p "${destination_directory}"
 
-          ls ${work_dir}/*.yaml | grep -v 'schema\|helm' | while read file;do
-            filename=$(basename "$file")
-            new_filename="${filename%.yaml}.json"
-            yq -o=json "${file}" | jq . > "${destination_directory}/${new_filename}"
-          done
-          
-          # Merge 2 files into one
-          jq -s "add" ${destination_directory}/*.json > "${destination_directory}/gke.json"
+          yq -o=json "${work_dir}/k8s-versions.yaml" | jq . > "${destination_directory}/azure.json"
 
       - name: Generate Matrix
         id: set-matrix
         run: |
-          cd /tmp/generated/gke
+          cd /tmp/generated/azure
 
           if [ "${{ github.event_name }}" == "schedule" ];then
-            cp gke.json /tmp/matrix.json
+            cp azure.json /tmp/matrix.json
           else
-            jq '{ "k8s": [ .k8s[] | select(.default) ], "config": .config}' gke.json > /tmp/matrix.json
+            jq '{ "include": [ .include[] | select(.default) ] }' azure.json > /tmp/matrix.json
           fi
 
           echo "Generated matrix:"
@@ -212,11 +207,11 @@ jobs:
   # This job is skipped when the workflow was triggered with the generic `/test`
   # trigger if the only modified files were under `test/` or `Documentation/`.
   installation-and-connectivity:
-    name: "Installation and Connectivity Test (${{ matrix.k8s.version }}, ${{ matrix.config.index }}, ${{ matrix.config.type }})"
+    name: "Installation and Connectivity Test"
     needs: [check_changes, setup-report, generate-matrix]
     if: |
       (github.event_name == 'issue_comment' && (
-        github.event.comment.body == '/ci-gke-1.11' ||
+        github.event.comment.body == '/ci-aks-1.11' ||
         (github.event.comment.body == '/test-backport-1.11' && needs.check_changes.outputs.tested == 'true')
       )) ||
       github.event_name == 'schedule' ||
@@ -231,7 +226,7 @@ jobs:
 
     steps:
       - name: Checkout main branch to access local actions
-        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
+        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
         with:
           ref: ${{ github.event.repository.default_branch }}
           persist-credentials: false
@@ -242,7 +237,7 @@ jobs:
         id: vars
         run: |
           SHA="${{ needs.setup-report.outputs.sha }}"
-          CILIUM_INSTALL_DEFAULTS="--cluster-name=${{ env.clusterName }}-${{ matrix.config.index }} \
+          CILIUM_INSTALL_DEFAULTS="--cluster-name=${{ env.name }} \
             --chart-directory=install/kubernetes/cilium \
             --helm-set=image.repository=quay.io/${{ env.QUAY_ORGANIZATION_DEV }}/cilium-ci \
             --helm-set=image.useDigest=false \
@@ -256,6 +251,8 @@ jobs:
             --helm-set=clustermesh.apiserver.image.useDigest=false \
             --helm-set=hubble.relay.image.repository=quay.io/${{ env.QUAY_ORGANIZATION_DEV }}/hubble-relay-ci \
             --helm-set=hubble.relay.image.tag=${SHA} \
+            --helm-set=debug.enabled=true \
+            --azure-resource-group ${{ env.name }}-${{ matrix.location }} \
             --wait=false \
             --rollback=false \
             --config monitor-aggregation=none \
@@ -263,11 +260,61 @@ jobs:
           HUBBLE_ENABLE_DEFAULTS="--chart-directory=install/kubernetes/cilium \
             --relay-image=quay.io/${{ env.QUAY_ORGANIZATION_DEV }}/hubble-relay-ci:${SHA} \
             --relay-version=${SHA}"
-          CONNECTIVITY_TEST_DEFAULTS="--flow-validation=disabled --hubble=false --collect-sysdump-on-failure \
-            --external-target google.com --external-cidr 8.0.0.0/8 --external-ip 8.8.8.8 --external-other-ip 8.8.4.4"
+          CONNECTIVITY_TEST_DEFAULTS="--flow-validation=disabled \
+            --hubble=false --collect-sysdump-on-failure --external-cidr 8.0.0.0/8 --external-ip 8.8.4.4 --external-other-ip 8.8.8.8"
           echo cilium_install_defaults=${CILIUM_INSTALL_DEFAULTS} >> $GITHUB_OUTPUT
           echo hubble_enable_defaults=${HUBBLE_ENABLE_DEFAULTS} >> $GITHUB_OUTPUT
           echo connectivity_test_defaults=${CONNECTIVITY_TEST_DEFAULTS} >> $GITHUB_OUTPUT
+
+      - name: Install Cilium CLI
+        uses: cilium/cilium-cli@9fcfef089e5b7dd3212f2eac21ba8cfae6f05cca # v0.14.7
+        with:
+          release-version: ${{ env.cilium_cli_version }}
+          ci-version: ${{ env.cilium_cli_ci_version }}
+
+      - name: Login to Azure
+        uses: azure/login@92a5484dfaf04ca78a94597f4f19fea633851fa2 # v1.4.7
+        with:
+          client-id: ${{ secrets.AZURE_PR_CLIENT_ID }}
+          tenant-id: ${{ secrets.AZURE_PR_TENANT_ID }}
+          subscription-id: ${{ secrets.AZURE_PR_SUBSCRIPTION_ID }}
+
+      - name: Display az version
+        run: |
+            az version
+
+      - name: Create AKS cluster
+        run: |
+          # Create group
+          az group create \
+            --name ${{ env.name }}-${{ matrix.location }} \
+            --location ${{ matrix.location }} \
+            --tags usage=${{ github.repository_owner }}-${{ github.event.repository.name }} owner=${{ needs.setup-report.outputs.owner }}
+
+          # Create AKS cluster
+          az aks create \
+            --resource-group ${{ env.name }}-${{ matrix.location }} \
+            --name ${{ env.name }} \
+            --location ${{ matrix.location }} \
+            --kubernetes-version ${{ matrix.version }} \
+            --network-plugin azure \
+            --node-count 2 \
+            ${{ env.cost_reduction }} \
+            --generate-ssh-keys
+
+      - name: Get cluster credentials
+        run: |
+          az aks get-credentials \
+            --resource-group ${{ env.name }}-${{ matrix.location }} \
+            --name ${{ env.name }}
+
+      - name: Wait for images to be available
+        timeout-minutes: 10
+        shell: bash
+        run: |
+          for image in cilium-ci operator-azure-ci hubble-relay-ci ; do
+            until docker manifest inspect quay.io/${{ env.QUAY_ORGANIZATION_DEV }}/$image:${{ needs.setup-report.outputs.sha }} &> /dev/null; do sleep 45s; done
+          done
 
       # Checkout source code to install Cilium using local Helm chart.
       - name: Checkout code
@@ -276,70 +323,9 @@ jobs:
           ref: ${{ needs.setup-report.outputs.sha }}
           persist-credentials: false
 
-      - name: Install Cilium CLI
-        uses: cilium/cilium-cli@9fcfef089e5b7dd3212f2eac21ba8cfae6f05cca # v0.14.7
-        with:
-          release-version: ${{ env.cilium_cli_version }}
-          ci-version: ${{ env.cilium_cli_ci_version }}
-
-      - name: Set up gcloud credentials
-        id: 'auth'
-        uses: google-github-actions/auth@35b0e87d162680511bf346c299f71c9c5c379033 # v1.1.1
-        with:
-          credentials_json: '${{ secrets.GCP_PR_SA_KEY }}'
-
-      - name: Set up gcloud CLI
-        uses: google-github-actions/setup-gcloud@e30db14379863a8c79331b04a9969f4c1e225e0b # v1.1.1
-        with:
-          project_id: ${{ secrets.GCP_PROJECT_ID }}
-          version: "405.0.0"
-
-      - name: Install gke-gcloud-auth-plugin
-        run: |
-          gcloud components install gke-gcloud-auth-plugin
-
-      - name: Display gcloud CLI info
-        run: |
-          gcloud info
-
-      - name: Create GKE cluster
-        run: |
-          gcloud container clusters create ${{ env.clusterName }}-${{ matrix.config.index }} \
-            --labels "usage=${{ github.repository_owner }}-${{ github.event.repository.name }},owner=${{ needs.setup-report.outputs.owner }}" \
-            --zone ${{ matrix.k8s.zone }} \
-            --cluster-version ${{ matrix.k8s.version }} \
-            --enable-ip-alias \
-            --create-subnetwork="range=/26" \
-            --cluster-ipv4-cidr="/21" \
-            --services-ipv4-cidr="/24" \
-            --image-type COS_CONTAINERD \
-            --num-nodes 2 \
-            --machine-type e2-custom-2-4096 \
-            --disk-type pd-standard \
-            --disk-size 10GB \
-            --node-taints node.cilium.io/agent-not-ready=true:NoExecute \
-            --preemptible
-
-      - name: Get cluster credentials
-        run: |
-          gcloud container clusters get-credentials ${{ env.clusterName }}-${{ matrix.config.index }} --zone ${{ matrix.k8s.zone }}
-
-      - name: Wait for images to be available
-        timeout-minutes: 10
-        shell: bash
-        run: |
-          for image in cilium-ci operator-generic-ci hubble-relay-ci ; do
-            until docker manifest inspect quay.io/${{ env.QUAY_ORGANIZATION_DEV }}/$image:${{ needs.setup-report.outputs.sha }} &> /dev/null; do sleep 45s; done
-          done
-
-      - name: Create custom IPsec secret
-        if: ${{ matrix.config.type == 'ipsec' || matrix.config.type == 'tunnel-ipsec' }}
-        run: |
-          kubectl create -n kube-system secret generic cilium-ipsec-keys --from-literal=keys="15 rfc4106(gcm(aes)) $(echo $(dd if=/dev/urandom count=20 bs=1 2> /dev/null | xxd -p -c 64)) 128"
-
       - name: Install Cilium
         run: |
-          cilium install ${{ steps.vars.outputs.cilium_install_defaults }} ${{ matrix.config.cilium-install-opts }}
+          cilium install ${{ steps.vars.outputs.cilium_install_defaults }}
 
       - name: Enable Relay
         run: |
@@ -359,11 +345,45 @@ jobs:
         run: |
           mkdir -p cilium-junits
 
-      - name: Run connectivity test (${{ matrix.k8s.version }}, ${{ matrix.config.index }}, ${{ matrix.config.type }})
+      - name: Run connectivity test (${{ join(matrix.*, ', ') }})
         run: |
           cilium connectivity test ${{ steps.vars.outputs.connectivity_test_defaults }} \
-          --junit-file "cilium-junits/${{ env.job_name }} (${{matrix.k8s.version}}, ${{matrix.config.index}}, ${{matrix.config.type}}).xml" \
-          --junit-property github_job_step="Run connectivity test (${{ matrix.k8s.version }}, ${{ matrix.config.index }}, ${{ matrix.config.type }})"
+          --junit-file "cilium-junits/${{ env.job_name }} (${{ join(matrix.*, ', ') }}) - 1.xml" \
+          --junit-property github_job_step="Run connectivity test (${{ join(matrix.*, ', ') }})"
+
+      - name: Clean up Cilium
+        run: |
+          pkill -f "cilium.*hubble.*port-forward|kubectl.*port-forward.*hubble-relay"
+          cilium uninstall --chart-directory=install/kubernetes/cilium --wait
+
+      - name: Create custom IPsec secret
+        run: |
+          kubectl create -n kube-system secret generic cilium-ipsec-keys --from-literal=keys="15 rfc4106(gcm(aes)) $(echo $(dd if=/dev/urandom count=20 bs=1 2> /dev/null | xxd -p -c 64)) 128"
+
+      - name: Install Cilium with encryption
+        run: |
+          cilium install ${{ steps.vars.outputs.cilium_install_defaults }} \
+            --encryption=ipsec
+
+      - name: Enable Relay
+        run: |
+          cilium hubble enable ${{ steps.vars.outputs.hubble_enable_defaults }}
+
+      - name: Wait for Cilium status to be ready
+        run: |
+          cilium status --wait
+
+      - name: Port forward Relay
+        run: |
+          cilium hubble port-forward&
+          sleep 10s
+          [[ $(pgrep -f "cilium.*hubble.*port-forward|kubectl.*port-forward.*hubble-relay" | wc -l) == 2 ]]
+
+      - name: Run connectivity test with IPSec (${{ join(matrix.*, ', ') }})
+        run: |
+          cilium connectivity test ${{ steps.vars.outputs.connectivity_test_defaults }} --force-deploy \
+          --junit-file "cilium-junits/${{ env.job_name }} (${{ join(matrix.*, ', ') }}) - 2.xml" \
+          --junit-property github_job_step="Run connectivity test with IPSec (${{ join(matrix.*, ', ') }})"
 
       - name: Post-test information gathering
         if: ${{ !success() }}
@@ -373,14 +393,11 @@ jobs:
           cilium sysdump --output-filename cilium-sysdump-final
         shell: bash {0} # Disable default fail-fast behaviour so that all commands run independently
 
-      - name: Clean up GKE
+      - name: Clean up AKS
         if: ${{ always() }}
         run: |
-          while [ "$(gcloud container operations list --zone ${{ matrix.k8s.zone }} --filter="status=RUNNING AND targetLink~${{ env.clusterName }}-${{ matrix.config.index }}" --format="value(name)")" ];do
-            echo "cluster has an ongoing operation, waiting for all operations to finish"; sleep 15
-          done
-          gcloud container clusters delete ${{ env.clusterName }}-${{ matrix.config.index }} --zone ${{ matrix.k8s.zone }} --quiet --async
-        shell: bash {0} # Disable default fail-fast behavior so that all commands run independently
+          az group delete --name ${{ env.name }}-${{ matrix.location }} --yes --no-wait
+        shell: bash {0} # Disable default fail-fast behaviour so that all commands run independently
 
       - name: Upload artifacts
         if: ${{ !success() }}
