ci-ipsec-e2e: Add more key types
[ upstream commit 5c988ee1546fdf9e1f220f1b95a7d57f0afd9e1b ]

Signed-off-by: Martynas Pumputis <m@lambda.lt>
Signed-off-by: Julian Wiedmann <jwi@isovalent.com>

diff --git a/.github/workflows/conformance-ipsec-e2e.yaml b/.github/workflows/conformance-ipsec-e2e.yaml
--- a/.github/workflows/conformance-ipsec-e2e.yaml
+++ b/.github/workflows/conformance-ipsec-e2e.yaml
@@ -83,6 +83,8 @@ jobs:
             tunnel: 'vxlan'
             encryption: 'ipsec'
             encryption-node: 'false'
+            key-one: 'gcm(aes)'
+            key-two: 'cbc(aes)'
             key-type-one: '+'
             key-type-two: '+'
 
@@ -94,6 +96,8 @@ jobs:
             tunnel: 'disabled'
             encryption: 'ipsec'
             encryption-node: 'false'
+            key-one: 'cbc(aes)'
+            key-two: 'cbc(aes)'
             key-type-one: '+'
             key-type-two: ''
 
@@ -106,6 +110,8 @@ jobs:
             encryption: 'ipsec'
             encryption-node: 'false'
             endpoint-routes: 'true'
+            key-one: 'gcm(aes)'
+            key-two: 'gcm(aes)'
             key-type-one: ''
             key-type-two: '+'
 
@@ -118,6 +124,8 @@ jobs:
             encryption: 'ipsec'
             encryption-node: 'false'
             endpoint-routes: 'true'
+            key-one: 'cbc(aes)'
+            key-two: 'gcm(aes)'
             key-type-one: ''
             key-type-two: ''
 
@@ -211,8 +219,16 @@ jobs:
         shell: bash
         run: |
           kubectl patch node kind-worker3 --type=json -p='[{"op":"add","path":"/metadata/labels/cilium.io~1no-schedule","value":"true"}]'
+
+          if [[ "${{ matrix.key-one }}" == "gcm(aes)" ]]; then
+            key="rfc4106(gcm(aes)) $(dd if=/dev/urandom count=20 bs=1 2> /dev/null | xxd -p -c 64) 128"
+          elif [[ "${{ matrix.key-one }}" == "cbc(aes)" ]]; then
+            key="hmac(sha256) $(dd if=/dev/urandom count=32 bs=1 2> /dev/null| xxd -p -c 64) cbc(aes) $(dd if=/dev/urandom count=32 bs=1 2> /dev/null| xxd -p -c 64)"
+          else
+            echo "Invalid key type"; exit 1
+          fi
           kubectl create -n kube-system secret generic cilium-ipsec-keys \
-            --from-literal=keys="3${{ matrix.key-type-one }} rfc4106(gcm(aes)) $(echo $(dd if=/dev/urandom count=20 bs=1 2> /dev/null | xxd -p -c 64)) 128"
+            --from-literal=keys="3${{ matrix.key-type-one }} ${key}"
 
           export CILIUM_CLI_MODE=helm
           ./cilium-cli install ${{ steps.cilium-config.outputs.config }}
@@ -239,7 +255,15 @@ jobs:
           operation-cmd: |
             KEYID=$(kubectl get secret -n kube-system cilium-ipsec-keys -o go-template --template={{.data.keys}} | base64 -d | grep -oP "^\d+")
             if [[ $KEYID -ge 15 ]]; then KEYID=0; fi
-            data=$(echo "{\"stringData\":{\"keys\":\"$((($KEYID+1)))${{ matrix.key-type-two }} "rfc4106\(gcm\(aes\)\)" 59f4d92cccede1b1abc920104ca61cd552782e12 128\"}}")
+
+            if [[ "${{ matrix.key-two }}" == "gcm(aes)" ]]; then
+              key="rfc4106(gcm(aes)) $(dd if=/dev/urandom count=20 bs=1 2> /dev/null | xxd -p -c 64) 128"
+            elif [[ "${{ matrix.key-two }}" == "cbc(aes)" ]]; then
+              key="hmac(sha256) $(dd if=/dev/urandom count=32 bs=1 2> /dev/null| xxd -p -c 64) cbc(aes) $(dd if=/dev/urandom count=32 bs=1 2> /dev/null| xxd -p -c 64)"
+            else
+              echo "Invalid key type"; exit 1
+            fi
+            data="{\"stringData\":{\"keys\":\"$((($KEYID+1)))${{ matrix.key-type-two }} ${key}\"}}"
             kubectl patch secret -n kube-system cilium-ipsec-keys -p="$data" -v=1
 
             # Compute number of expected keys during key rotation depending on
