.github: Prepare workflows for tests with a 3rd node
The 3rd node does not run Cilium and will be used in the connectivity
tests with `--nodes-without-cilium=kind-worker2`.

The same was done in the cilium/cilium-cli repo, see
https://github.com/cilium/cilium-cli/pull/1494.

Signed-off-by: Chris Tarazi <chris@isovalent.com>

diff --git a/.github/workflows/conformance-kind.yaml b/.github/workflows/conformance-kind.yaml
--- a/.github/workflows/conformance-kind.yaml
+++ b/.github/workflows/conformance-kind.yaml
@@ -48,6 +48,10 @@ jobs:
             SHA=${{ github.sha }}
           fi
 
+          # To add more elements, keep it comma-separated.
+          NODES_WITHOUT_CILIUM=chart-testing-worker2
+          echo "NODES_WITHOUT_CILIUM=${NODES_WITHOUT_CILIUM}" >> $GITHUB_ENV
+
           # Note: On Kind, we install Cilium with HostPort (portmap CNI chaining) enabled,
           # to ensure coverage of that feature in cilium connectivity test
           CILIUM_INSTALL_DEFAULTS="--chart-directory=install/kubernetes/cilium \
@@ -66,6 +70,7 @@ jobs:
             --helm-set cni.chainingMode=portmap \
             --helm-set loadBalancer.l7.backend=envoy \
             --helm-set tls.secretsBackend=k8s \
+            --nodes-without-cilium=${NODES_WITHOUT_CILIUM} \
             --wait=false \
             --rollback=false \
             --config monitor-aggregation=none \
@@ -100,6 +105,70 @@ jobs:
           version: ${{ env.kind_version }}
           config: ${{ env.kind_config }}
 
+      # - name: Label nodes
+      #   if: ${{ matrix.mode == 'helm' }}
+      #   run: |
+      #     IFS=',' read -ra nodes <<< "$NODES_WITHOUT_CILIUM"
+      #     for node in "${nodes[@]}"; do
+      #       kubectl label nodes "${node}" cilium.io/no-schedule=true
+      #     done
+
+      # Taken from cilium/cilium-cli/.github/workflows/kind.yaml.
+      #
+      # This is needed for the tests that run with nodes without Cilium.
+      - name: Install static routes
+        id: statiic-routes
+        run: |
+          EXTERNAL_FROM_CIDRS=($(kubectl get nodes -o jsonpath='{range .items[*]}{.spec.podCIDR}{"\n"}{end}'))
+          EXTERNAL_NODE_IPS=() # Nodes IPs are collected to be passed to the Cilium CLI later on.
+
+          # Loop over each pod CIDR from all nodes.
+          for i in "${!EXTERNAL_FROM_CIDRS[@]}"; do
+            EXTERNAL_FROM_CIDR=${EXTERNAL_FROM_CIDRS[i]}
+
+            if [[ $EXTERNAL_FROM_CIDR =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+/[0-9]+$ ]]; then
+              IP_FAMILY="v4"
+            elif [[ $EXTERNAL_FROM_CIDR =~ ^[0-9a-fA-F:]+/[0-9]+$ ]]; then
+              IP_FAMILY="v6"
+            else
+              echo "ERROR: Malformed pod CIDR '${EXTERNAL_FROM_CIDR}'" >&2
+              exit 1
+            fi
+
+            IFS=',' read -ra NODES_WITHOUT <<< "$NODES_WITHOUT_CILIUM" # Split by comma into an array
+            for WITHOUT in "${NODES_WITHOUT[@]}"; do
+              # Fetch node with a specific pod CIDR.
+              node=$(kubectl get nodes -o jsonpath="{range .items[?(@.spec.podCIDR == '$EXTERNAL_FROM_CIDR')]}{@.metadata.name}{end}")
+              if [[ -z "$node" ]]; then
+                echo "ERROR: Could not find node with .spec.podCIDR matching ${EXTERNAL_FROM_CIDR}" >&2
+                exit 1
+              fi
+              for NODE_IP in $(kubectl get node "$node" -o jsonpath="{.status.addresses[?(@.type == 'InternalIP')].address}"); do
+                # Skip if the node IP's family mismatches with pod CIDR's
+                # family. Cannot create a route with the gateway IP family
+                # mismatching the subnet.
+                if [[ "$IP_FAMILY" == "v4" && ! "$NODE_IP" =~ \. ]]; then
+                  continue
+                elif [[ "$IP_FAMILY" == "v6" && ! "$NODE_IP" =~ \: ]]; then
+                  continue
+                fi
+                # Install static route on the host, towards the pod CIDR via the node IP.
+                docker exec "$WITHOUT" ip route replace "${EXTERNAL_FROM_CIDR}" via "${NODE_IP}"
+                EXTERNAL_NODE_IPS+=("${NODE_IP}")
+              done
+            done
+          done
+
+          # Join the elements with a comma delimiter, or leave them unmodified
+          # if there's only one element so that it can be passed properly to
+          # the CLI.
+          if [[ ${#EXTERNAL_NODE_IPS[@]} -eq 1 ]]; then
+            EXTERNAL_NODE_IPS_PARAM="${EXTERNAL_NODE_IPS[0]}"
+          else
+            EXTERNAL_NODE_IPS_PARAM=$(IFS=','; echo "${EXTERNAL_NODE_IPS[*]}")
+          fi
+          echo external_from_cidrs_param="--external-from-cidrs=${EXTERNAL_NODE_IPS_PARAM}" >> $GITHUB_OUTPUT
+
       - name: Wait for images to be available
         timeout-minutes: 30
         shell: bash
@@ -124,7 +193,7 @@ jobs:
 
       - name: Run connectivity test
         run: |
-          cilium connectivity test ${{ steps.vars.outputs.connectivity_test_defaults }}
+          cilium connectivity test ${{ steps.vars.outputs.connectivity_test_defaults }} ${{steps.statiic-routes.outputs.external_from_cidrs_param }}
 
       - name: Clean up Cilium
         run: |
@@ -148,7 +217,7 @@ jobs:
 
       - name: Run connectivity test
         run: |
-          cilium connectivity test ${{ steps.vars.outputs.connectivity_test_defaults }} --force-deploy
+          cilium connectivity test ${{ steps.vars.outputs.connectivity_test_defaults }} ${{steps.statiic-routes.outputs.external_from_cidrs_param }} --force-deploy
 
       - name: Post-test information gathering
         if: ${{ !success() }}
