CI: add job name validation
[ upstream commit 3f5e735cdb303cdcba019a02f46cc781006dc386 ]

This commit adds validation for `commit_status_start` job.
This job is used in workflows that is triggered by Ariane to set the run status to pending.
Ariane is going to depend on this job being existed and its name is "Commit Status Start".
Also, the trigger syntax of `link-build-commits.yaml` is changed because `yq` is throwing an error.

Signed-off-by: Birol Bilgin <birol@cilium.io>
Signed-off-by: Gilberto Bertin <jibi@cilium.io>

diff --git a/.github/workflows/lint-workflows.yaml b/.github/workflows/lint-workflows.yaml
--- a/.github/workflows/lint-workflows.yaml
+++ b/.github/workflows/lint-workflows.yaml
@@ -225,3 +225,27 @@ jobs:
             fi
           done
           exit ${EXIT}
+
+      - name: Validate Commit Status Start Job
+        shell: bash
+        run: |
+          EXIT=0
+          cd src/github.com/cilium/cilium/.github/workflows
+          for FILE in *.yaml; do
+            # we only care about workflows that has ariane workflow_dispatch events
+            IS_ARIANE_DISPATCH=$(yq '.on.workflow_dispatch.inputs.PR-number' $FILE)
+            if [ "$IS_ARIANE_DISPATCH" == "null" ]; then
+                continue
+            fi
+            JOB=$(yq '.jobs | to_entries | .[] | select(.key == "commit-status-start")' $FILE)
+            if [ "$JOB" == "" ]; then
+                echo "commit-status-start job is missing in file $FILE"
+                EXIT=1
+            fi
+            JOB_NAME=$(echo "${JOB}" | yq '.value.name')
+            if [ "$JOB_NAME" != "Commit Status Start" ]; then
+                echo "commit-status-start job name must be set as 'Commit Status Start' in file $FILE"
+                EXIT=1
+            fi
+          done
+          exit ${EXIT}
