ci: Use conn-disrupt-test-{setup,check} for ci-ipsec-upgrade
[ upstream commit: 364ff9e ]

Signed-off-by: gray <gray.liang@isovalent.com>

diff --git a/.github/workflows/tests-ipsec-upgrade.yaml b/.github/workflows/tests-ipsec-upgrade.yaml
--- a/.github/workflows/tests-ipsec-upgrade.yaml
+++ b/.github/workflows/tests-ipsec-upgrade.yaml
@@ -368,41 +368,56 @@ jobs:
           ./cilium-cli connectivity test --include-conn-disrupt-test --conn-disrupt-test-setup \
             --conn-disrupt-dispatch-interval 0ms
 
-      - name: Upgrade Cilium & Test (${{ matrix.name }})
+      - name: Setup conn-disrupt-test before upgrading (${{ matrix.name }})
         if: ${{ steps.vars.outputs.downgrade_version != '' }}
-        uses: ./.github/actions/conn-disrupt-test
-        with:
-          job-name: ipsec-upgrade-${{ matrix.name }}
-          operation-cmd: |
-            CILIUM_CLI_MODE=helm ./cilium-cli upgrade \
-              ${{ steps.cilium-newest-config.outputs.config }}
+        uses: ./.github/actions/conn-disrupt-test-setup
 
-            ./cilium-cli status --wait
-            kubectl get pods --all-namespaces -o wide
-            kubectl -n kube-system exec daemonset/cilium -c cilium-agent -- cilium status
-
-      - name: Downgrade Cilium to ${{ steps.vars.outputs.downgrade_version }} & Test (${{ matrix.name }})
+      - name: Upgrade Cilium (${{ matrix.name }})
         if: ${{ steps.vars.outputs.downgrade_version != '' }}
-        uses: ./.github/actions/conn-disrupt-test
+        shell: bash
+        run: |
+          CILIUM_CLI_MODE=helm ./cilium-cli upgrade \
+            ${{ steps.cilium-newest-config.outputs.config }}
+
+          ./cilium-cli status --wait
+          kubectl get pods --all-namespaces -o wide
+          kubectl -n kube-system exec daemonset/cilium -c cilium-agent -- cilium status
+
+      - name: Run tests after upgrading (${{ matrix.name }})
+        if: ${{ steps.vars.outputs.downgrade_version != '' }}
+        uses: ./.github/actions/conn-disrupt-test-check
         with:
-          job-name: ipsec-downgrade-${{ matrix.name }}
-          # Disable no-unexpected-packet-drops (formerly no-missed-tail-calls)
-          # due to https://github.com/cilium/cilium/issues/26739
-          extra-connectivity-test-flags: '--expected-drop-reasons "+Missed tail call" ${{ steps.vars.outputs.expected_drop_reasons }}'
-          operation-cmd: |
-            CILIUM_CLI_MODE=helm ./cilium-cli upgrade \
-              ${{ steps.cilium-stable-config.outputs.config }}
+          job-name: cilium-upgrade-${{ matrix.name }}
+          full-test: 'true'
 
-            ./cilium-cli status --wait
-            kubectl get pods --all-namespaces -o wide
-            kubectl -n kube-system exec daemonset/cilium -c cilium-agent -- cilium status
+      - name: Setup conn-disrupt-test before downgrading
+        if: ${{ steps.vars.outputs.downgrade_version != '' }}
+        uses: ./.github/actions/conn-disrupt-test-setup
 
-            # 1.12 is EOL, we have to run commands manually to clean up stale routing rules
-            cilium_pods=$(kubectl -nkube-system get po -l k8s-app=cilium --no-headers -o custom-columns=":metadata.name")
-            for cilium_pod in $cilium_pods; do
-              kubectl -nkube-system exec $cilium_pod -- ip -4 rule delete fwmark 0xB00/0xF00 lookup 2005 2>/dev/null || true
-              kubectl -nkube-system exec $cilium_pod -- ip -6 rule delete fwmark 0xB00/0xF00 lookup 2005 2>/dev/null || true
-            done
+      - name: Downgrade Cilium to ${{ steps.vars.outputs.downgrade_version }} (${{ matrix.name }})
+        if: ${{ steps.vars.outputs.downgrade_version != '' }}
+        shell: bash
+        run: |
+          CILIUM_CLI_MODE=helm ./cilium-cli upgrade \
+            ${{ steps.cilium-stable-config.outputs.config }}
+
+          ./cilium-cli status --wait
+          kubectl get pods --all-namespaces -o wide
+          kubectl -n kube-system exec daemonset/cilium -c cilium-agent -- cilium status
+
+          # 1.12 is EOL, we have to run commands manually to clean up stale routing rules
+          cilium_pods=$(kubectl -nkube-system get po -l k8s-app=cilium --no-headers -o custom-columns=":metadata.name")
+          for cilium_pod in $cilium_pods; do
+            kubectl -nkube-system exec $cilium_pod -- ip -4 rule delete fwmark 0xB00/0xF00 lookup 2005 2>/dev/null || true
+            kubectl -nkube-system exec $cilium_pod -- ip -6 rule delete fwmark 0xB00/0xF00 lookup 2005 2>/dev/null || true
+          done
+
+      - name: Check conn-disrupt-test after downgrading
+        if: ${{ steps.vars.outputs.downgrade_version != '' }}
+        uses: ./.github/actions/conn-disrupt-test-check
+        with:
+          job-name: cilium-downgrade-${{ matrix.name }}
+          full-test: 'true'
 
       - name: Fetch artifacts
         if: ${{ steps.vars.outputs.downgrade_version != '' && !success() }}
